import { build } from 'esbuild';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { isBuiltin } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const result = await build({
  absWorkingDir: root, entryPoints: ['src/cli.ts'], outfile: 'dist/twiglet.cjs',
  bundle: true, platform: 'node', format: 'cjs', target: 'node22',
  write: false, metafile: true, minify: false, legalComments: 'inline', charset: 'utf8',
  banner: { js: '// Generated by npm run build. Edit src/, not this file.\n' +
    'if (Number(process.versions.node.split(".")[0]) < 22) { console.error("Twiglet requires Node 22 or newer; no runtime will be downloaded."); process.exit(1); }' },
});

for (const output of Object.values(result.metafile.outputs)) {
  for (const dependency of output.imports) {
    if (dependency.external && !isBuiltin(dependency.path)) throw new Error(`Unbundled dependency: ${dependency.path}`);
  }
}
const packages = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const match = input.replaceAll('\\', '/').match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)/);
  if (match) packages.add(match[1]);
}
const notices = ['Third-party code bundled in twiglet.cjs. Generated by npm run build.\n'];
for (const directory of [...packages].sort()) {
  const location = path.join(root, directory);
  const pkg = JSON.parse(await readFile(path.join(location, 'package.json'), 'utf8'));
  const licenses = (await readdir(location)).filter((name) => /^(license|licence|copying|notice)([.-]|$)/i.test(name)).sort();
  if (!licenses.length) throw new Error(`No license text found for ${pkg.name}`);
  notices.push(`\n===== ${pkg.name}@${pkg.version} (${pkg.license}) =====\n`);
  for (const license of licenses) notices.push((await readFile(path.join(location, license), 'utf8')).replaceAll('\r\n', '\n').trim() + '\n');
}
const outputs = new Map([
  ['dist/twiglet.cjs', result.outputFiles[0].text],
  ['dist/THIRD_PARTY_NOTICES.txt', notices.join('\n')],
]);
if (process.argv.includes('--check')) {
  for (const [name, content] of outputs) {
    const actual = await readFile(path.join(root, name), 'utf8').catch(() => '');
    if (actual !== content) throw new Error(`${name} is stale. Run npm run build and include the output with source changes.`);
  }
  console.log('Distribution matches source and locked dependencies.');
} else {
  await mkdir(path.join(root, 'dist'), { recursive: true });
  for (const [name, content] of outputs) await writeFile(path.join(root, name), content);
  console.log('Built dist/twiglet.cjs and third-party notices.');
}
